-- CREATING THREE TABLES

-- hepatitis_enrollments
CREATE TABLE IF NOT EXISTS hepatitis_enrollments (
    (
    id                               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                             VARCHAR(255),
    facility_id                       BIGINT,
    created_by                        VARCHAR(255)                            NOT NULL,
    created_date                      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by                  VARCHAR(255)                            NOT NULL,
    last_modified_date                TIMESTAMP WITHOUT TIME ZONE,
    person_uuid                       VARCHAR(255),
    core_entry_point                  VARCHAR(255),
    sex                               VARCHAR(255),
    pregnancy                         INTEGER,
    weight                            DOUBLE PRECISION,
    height                            DOUBLE PRECISION,
    bmi                               DOUBLE PRECISION,
    hepatitis_b                       VARCHAR(255),
    breastfeeding                     VARCHAR(255),
    history_of_using_abused_substance VARCHAR(255),
    screening                         JSONB,
    CONSTRAINT pk_hepatitis_enrollments PRIMARY KEY (id)
    );

-- hepatitis_diagnosis
CREATE TABLE IF NOT EXISTS hepatitis_diagnosis
     (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                VARCHAR(255),
    facility_id         BIGINT,
    created_by          VARCHAR(255)                            NOT NULL,
    created_date        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by    VARCHAR(255)                            NOT NULL,
    last_modified_date  TIMESTAMP WITHOUT TIME ZONE,
    enrollment_uuid     BIGINT,
    hepatitis_b_test    JSONB,
    hepatitis_c_test    JSONB,
    clinical_parameters JSONB,
    CONSTRAINT pk_hepatitis_diagnosis PRIMARY KEY (id)
    );
    ALTER TABLE hepatitis_diagnosis
    ADD CONSTRAINT FK_HEPATITIS_DIAGNOSIS_ON_ENROLLMENT_UUID FOREIGN KEY (enrollment_uuid) REFERENCES hepatitis_enrollments (uuid);

-- hepatitis_treatments
CREATE TABLE IF NOT EXISTS hepatitis_treatments
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                  VARCHAR(255),
    facility_id           BIGINT,
    created_by            VARCHAR(255)                            NOT NULL,
    created_date          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by      VARCHAR(255)                            NOT NULL,
    last_modified_date    TIMESTAMP WITHOUT TIME ZONE,
    enrollment_uuid       BIGINT,
    hepatitis_b_treatment JSONB,
    hepatitis_c_treatment JSONB,
    CONSTRAINT pk_hepatitis_treatments PRIMARY KEY (id)
    );

    ALTER TABLE hepatitis_treatments
    ADD CONSTRAINT FK_HEPATITIS_TREATMENTS_ON_ENROLLMENT_UUID FOREIGN KEY (enrollment_uuid) REFERENCES hepatitis_enrollments (uuid);