-- CREATING THREE TABLES

-- hepatitis_enrollments
CREATE TABLE IF NOT EXISTS hepatitis_enrollments (
                                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                                     uuid TEXT NOT NULL,
                                                     person_uuid TEXT NOT NULL,
                                                     sex TEXT NULL,
                                                     pregancy TEXT,
                                                     weight DECIMAL,
                                                     height DECIMAL,
                                                     bmi DECIMAL,
                                                     hepatitis_b TEXT,
                                                     breastfeeding TEXT,
                                                     history_of_abused_substance TEXT,
                                                     screening JSONB,
                                                     created_by TEXT,
                                                     created_date TIMESTAMP WITHOUT TIME ZONE,
                                                     last_modified_date TIMESTAMP WITHOUT TIME ZONE,
                                                     last_modified_by TEXT,

                                                     CONSTRAINT pk_hepatitis_enrollments PRIMARY KEY (id)
    );

-- hepatitis_diagnosis
CREATE TABLE IF NOT EXISTS hepatitis_diagnosis (
                                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                                   uuid TEXT NOT NULL,
                                                   hepatitis_b_test JSONB,
                                                   hepatitis_c_test JSONB,
                                                   clinical_parameters JSONB,
                                                   created_by TEXT,
                                                   created_date TIMESTAMP WITHOUT TIME ZONE,
                                                   last_modified_date TIMESTAMP WITHOUT TIME ZONE,
                                                   last_modified_by TEXT,

                                                   CONSTRAINT pk_hepatitis_diagnosis PRIMARY KEY (id)
    );

-- hepatitis_treatments
CREATE TABLE IF NOT EXISTS hepatitis_treatments (
                                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                                    uuid TEXT NOT NULL,
                                                    hepatitis_b_treatment JSONB,
                                                    hepatitis_c_treatment JSONB,
                                                    created_by TEXT,
                                                    created_date TIMESTAMP WITHOUT TIME ZONE,
                                                    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
                                                    last_modified_by TEXT,

                                                    CONSTRAINT pk_hepatitis_treatments PRIMARY KEY (id)
    );

ALTER TABLE hepatitis_enrollments
    ADD CONSTRAINT uc_hepatitis_enrollment_uuid UNIQUE(uuid);

ALTER TABLE hepatitis_enrollments
    ADD CONSTRAINT hepatitis_enrollment_person_FK_uuid
        FOREIGN KEY (person_uuid)
            REFERENCES patient_person (uuid);

ALTER TABLE hepatitis_diagnosis
    ADD CONSTRAINT hepatitis_diagnosis_hepatitis_enrollments_FK_uuid
        FOREIGN KEY (uuid)
            REFERENCES hepatitis_enrollments (uuid);

ALTER TABLE hepatitis_treatments
    ADD CONSTRAINT hepatitis_treatments_hepatitis_enrollments_FK_uuid
        FOREIGN KEY (uuid)
            REFERENCES hepatitis_enrollments (uuid);