-- CREATING THREE TABLES

-- hepatitis_enrollments
CREATE TABLE IF NOT EXISTS hepatitis_enrollments (
    id                               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                             VARCHAR(255) NOT NULL,
    archived                          INTEGER                                 NOT NULL,
    facility_id                       BIGINT,
    created_by                        VARCHAR(255)                            NOT NULL,
    created_date                      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by                  VARCHAR(255)                            NOT NULL,
    last_modified_date                TIMESTAMP WITHOUT TIME ZONE,
    person_uuid                       VARCHAR(255),
    core_entry_point                  VARCHAR(255),
    sex                               VARCHAR(255),
    pregnancy                         VARCHAR(25),
    weight                            DOUBLE PRECISION,
    height                            DOUBLE PRECISION,
    bmi                               DOUBLE PRECISION,
    hepatitis_b                       VARCHAR(255),
    breastfeeding                     VARCHAR(255),
    history_of_using_abused_substance VARCHAR(255),
    screening                         JSONB,
    latitude                          varchar(255),
    longitude                         varchar(255),
    source                            varchar(25),
    care_entry_point                  varchar(255),
    CONSTRAINT pk_hepatitis_enrollments PRIMARY KEY (id),
    CONSTRAINT uc_hepatitis_enrollments_uuid UNIQUE (uuid)
    );

-- hepatitis_diagnosis
CREATE TABLE IF NOT EXISTS hepatitis_diagnosis
     (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                VARCHAR(255) NOT NULL,
    archived            INTEGER                                 NOT NULL,
    facility_id         BIGINT,
    created_by          VARCHAR(255)                            NOT NULL,
    created_date        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by    VARCHAR(255)                            NOT NULL,
    last_modified_date  TIMESTAMP WITHOUT TIME ZONE,
    enrollment_uuid     VARCHAR(255) NOT NULL,
    hepatitis_b_test    JSONB,
    hepatitis_c_test    JSONB,
    clinical_parameters JSONB,
    hepatitis_enrollment_uuid character varying COLLATE pg_catalog."default",
    latitude                          varchar(255),
    longitude                         varchar(255),
    source                            varchar(25),
    ast_plt_alt JSONB,
    CONSTRAINT pk_hepatitis_diagnosis PRIMARY KEY (id),
    CONSTRAINT uc_hepatitis_diagnosis_uuid UNIQUE (uuid),
    CONSTRAINT FK_HEPATITIS_DIAGNOSIS_ON_ENROLLMENT_UUID FOREIGN KEY (enrollment_uuid) REFERENCES hepatitis_enrollments (uuid),
    CONSTRAINT hepatitis_diagnosis_hepatitis_enrollment_uuid_fk FOREIGN KEY (hepatitis_enrollment_uuid) REFERENCES hepatitis_enrollments (uuid)

    );

-- hepatitis_treatments
CREATE TABLE IF NOT EXISTS hepatitis_treatments
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                  VARCHAR(255) NOT NULL,
    facility_id           BIGINT,
    archived            INTEGER                                 NOT NULL,
    created_by            VARCHAR(255)                            NOT NULL,
    created_date          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by      VARCHAR(255)                            NOT NULL,
    last_modified_date    TIMESTAMP WITHOUT TIME ZONE,
    enrollment_uuid       VARCHAR(255) NOT NULL,
    hepatitis_b_treatment JSONB,
    hepatitis_c_treatment JSONB,
    latitude                          varchar(255),
    longitude                         varchar(255),
    source                            varchar(25),
    CONSTRAINT pk_hepatitis_treatments PRIMARY KEY (id),
    CONSTRAINT uc_hepatitis_treatments_uuid UNIQUE (uuid),
    CONSTRAINT FK_HEPATITIS_TREATMENTS_ON_ENROLLMENT_UUID FOREIGN KEY (enrollment_uuid) REFERENCES hepatitis_enrollments (uuid)
    );

-- hepatitis_followups
CREATE TABLE IF NOT EXISTS hepatitis_followups
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                  VARCHAR(255) NOT NULL,
    facility_id           BIGINT,
    archived            INTEGER                                 NOT NULL,
    created_by            VARCHAR(255)                            NOT NULL,
    created_date          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by      VARCHAR(255)                            NOT NULL,
    last_modified_date    TIMESTAMP WITHOUT TIME ZONE,
    enrollment_uuid       VARCHAR(255) NOT NULL,
    preliminary JSONB,
    clinical_parameters JSONB,
    appointment JSONB,
    CONSTRAINT pk_hepatitis_followups PRIMARY KEY (id),
    CONSTRAINT uc_hepatitis_followups_uuid UNIQUE (uuid),
    CONSTRAINT FK_HEPATITIS_FOLLOWUPS_ON_ENROLLMENT_UUID FOREIGN KEY (enrollment_uuid) REFERENCES hepatitis_enrollments (uuid)
    );
