CREATE TABLE hepatitis_enrollment
(
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                          UUID UNIQUE,
    hospital_number               VARCHAR(255),
    surname                       VARCHAR(255),
    other_name                    VARCHAR(255),
    phone_number                  VARCHAR(255),
    sex                           INTEGER,
    address                       VARCHAR(255),
    landmark                      VARCHAR(255),
    country                       VARCHAR(255),
    state                         VARCHAR(255),
    lga                           VARCHAR(255),
    date_of_birth                 date,
    age                           INTEGER,
    occupation                    INTEGER,
    marital_status                INTEGER,
    education                     INTEGER,
    entry_point                   INTEGER,
    weight                        VARCHAR(255),
    height                        VARCHAR(255),
    bmi                           VARCHAR(255),
    hepatitis_b                   INTEGER,
    pregnant                      BOOLEAN,
    breast_feeding                BOOLEAN,
    history_of_drug_abuse         BOOLEAN,
    screening_date_of_hepatitis_b date,
    screening_of_hepatitis_c      INTEGER,
    CONSTRAINT pk_hepatitis_enrollment PRIMARY KEY (id)
);

CREATE TABLE hepatitis_diagnosis
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    enrollment_id                UUID                                  NOT NULL,
    date_hbv_test_requested      date,
    date_hbv_sample_requested    date,
    date_hbv_dna_result_reported date,
    hbv_dna                      INTEGER,
    hbsag_qualification          VARCHAR(255),
    hbe_ag                       INTEGER,
    anti_hdv                     INTEGER,
    treatment_eligible           BOOLEAN,
    pmtct_eligible               BOOLEAN,
    comment                      VARCHAR(255),
    hcv_rna                      INTEGER,
    hepatitis_coinfection        INTEGER,
    commobidities                VARCHAR(255),
    ast                          VARCHAR(255),
    alt                          VARCHAR(255),
    pst                          VARCHAR(255),
    total_bilirubin              VARCHAR(255),
    direct_bilirubin             VARCHAR(255),
    apri_score                   VARCHAR(255),
    fib_4                        VARCHAR(255),
    prothrombin_time             VARCHAR(255),
    urea                         VARCHAR(255),
    creatinine                   VARCHAR(255),
    afp                          VARCHAR(255),
    fibroscan                    VARCHAR(255),
    ultrasound_scan              VARCHAR(255),
    ascites                      BOOLEAN,
    grade_of_encephalopathy      INTEGER,
    child_pugh_score             VARCHAR(255),
    liver_biopsy_stage           INTEGER,
    diagnosis                    INTEGER,
    CONSTRAINT pk_hepatitis_diagnosis PRIMARY KEY (id)
);

ALTER TABLE hepatitis_diagnosis
    ADD FOREIGN KEY (enrollment_id)
        REFERENCES hepatitis_enrollment (uuid)
    NOT VALID;

-- ALTER TABLE hepatitis_diagnosis
--     ADD CONSTRAINT FK_HEPATITIS_DIAGNOSIS_ON_ENROLLMENT FOREIGN KEY (enrollment_id) REFERENCES hepatitis_enrollment (uuid);

CREATE TABLE hepatitis_treatment
(
    id                                  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    enrollment_id                       UUID                                  NOT NULL,
    experience_hepatitis_b              BOOLEAN,
    new_regime_hepatitis_b              VARCHAR(255),
    history_adverse_effect_hepatitis_b  BOOLEAN,
    new_regime_switch_hepatitis_b       INTEGER,
    date_started_hepatitis_b            date,
    adverse_effect_reported_hepatitis_b BOOLEAN,
    reason_for_switch_hepatitis_b       VARCHAR(255),
    date_stop_hepatitis_b               date,
    reason_for_treatment_hepatitis_b    VARCHAR(255),
    comment_hepatitis_b                 VARCHAR(255),
    experience_hepatitis_c              BOOLEAN,
    date_started_hepatitis_c            date,
    date_completed_hepatitis_c          date,
    prescribed_hepatitis_c              INTEGER,
    history_adverse_effect_hepatitis_c  BOOLEAN,
    new_regime_switch_hepatitis_c       INTEGER,
    date_started_switch_hepatitis_c     date,
    date_stop_switch_hepatitis_c        date,
    prescribed_switch_hepatitis_c       INTEGER,
    adverse_effect_hepatitis_c          BOOLEAN,
    date_tested_svr                     date,
    hvc_rna_svr                         INTEGER,
    hvc_rna_svr_value                   VARCHAR(255),
    retreatment_date_tested_svr         date,
    retreatment_hcv_rna_svr             VARCHAR(255),
    new_regime_hcv                      INTEGER,
    new_prescribed_duration_hcv         INTEGER,
    date_started_hcv                    date,
    date_stopped_hcv                    date,
    adverse_effect_hcv                  VARCHAR(255),
    hcvgenotype                         VARCHAR(255),
    CONSTRAINT pk_hepatitis_treatment PRIMARY KEY (id)
);

ALTER TABLE hepatitis_treatment
    ADD FOREIGN KEY (enrollment_id)
        REFERENCES hepatitis_enrollment (uuid)
    NOT VALID;
--
-- ALTER TABLE hepatitis_treatment
--     ADD CONSTRAINT FK_HEPATITIS_TREATMENT_ON_ENROLLMENT FOREIGN KEY (enrollment_id) REFERENCES hepatitis_enrollment (uuid);