import { useFormik } from "formik";
import * as yup from "yup";

const invalidTextPrompt = "Invalid input type";
const requiredTextPrompt = "field is required";

export const useValidateForm1ValuesHook = (onSubmit) => {
  const form1InitialValues = {
    stateId: "",
    otherName: "",
    countryId: "",
    coreEntryPoint: "",
    pregnancy: "",
    weight: "",
    height: "",
    hepatitisB: "",
    breastfeeding: "",
    historyOfUsingAbusedSubstance: "",
    dateOfFirstHepatitisBPositiveScreening: "",
    hepatitisC: "",
    surname: "",
    firstName: "",
    dateOfBirth: "",
    maritalStatusId: "",
    phone: "",
    ninNumber: "",
    isDateOfBirthEstimated: "",
    educationId: "",
    employmentStatusId: "",
    dateOfRegistration: "",
  };

  const Form1ValidationSchema = yup.object({
    stateId: isOperationUpdate ? yup.mixed() : yup.number(),
    countryId: isOperationUpdate ? yup.mixed() : yup.number(),
    educationId: isOperationUpdate ? yup.mixed() : yup.number(),
    employmentStatusId: isOperationUpdate ? yup.mixed() : yup.number(),
    coreEntryPoint: isOperationUpdate ? yup.mixed() : yup.number(),
    pregnancy: isOperationUpdate ? yup.mixed() : yup.number(),
    weight: isOperationUpdate ? yup.mixed() : yup.number(),
    height: isOperationUpdate ? yup.mixed() : yup.number(),
    hepatitisB: isOperationUpdate ? yup.mixed() : yup.number(),
    breastfeeding: isOperationUpdate ? yup.mixed() : yup.number(),
    historyOfUsingAbusedSubstance: isOperationUpdate ? yup.mixed() : yup.number(),
    dateOfFirstHepatitisBPositiveScreening: yup.date(),
    hepatitisC: isOperationUpdate ? yup.mixed() : yup.number(),
    surname: isOperationUpdate ? yup.mixed() : yup.number(),
    firstName: isOperationUpdate ? yup.mixed() : yup.number(),
    otherName: isOperationUpdate ? yup.mixed() : yup.number(),
    dateOfBirth: yup.date(),
    dateOfRegistration: yup.date(),
    maritalStatusId: isOperationUpdate ? yup.mixed() : yup.number(),
    sexId: isOperationUpdate ? yup.mixed() : yup.number(),
    phone: isOperationUpdate ? yup.mixed() : yup.number(),
    ninNumber: isOperationUpdate ? yup.mixed() : yup.number(),
    isDateOfBirthEstimated: yup.boolean(),
  });

  const formik = useFormik({
    initialValues: form1InitialValues,
    onSubmit,
    validationSchema: Form1ValidationSchema,
  });
  return { formik };
};

export const useValidateFollowupFormValuesHook = (onSubmit, operation) => {
  const isOperationUpdate = operation === "update" ? true: false
  const followupFormIntialValue = {
    fuDateOfVisit: "",
    fuWeight: "",
    fuHeight: "",
    // fuBmi: "",
    fuBloodPressure: "",
    fuHbsag: "",
    fuHbsagQuantification: "",
    fuHbeag: "",
    fuHbvDna: "",
    fuHbvDnaStatus: "",
    fuAlt: "",
    fuAst: "",
    fuPlt: "",
    fuTotalBilirubin: "",
    fuDirectBilirubin: "",
    fuAlbumin: "",
    fuApriScore: "",
    fuFib4: "",
    fuProthrombinTime: "",
    fuUrea: "",
    fuCreatinine: "",
    fuUltrasoundScan: "",
    fuAfp: "",
    fuFibroscan: "",
    fuCtScan: "",
    fuAscites: "",
    fuSeverityOfAscites: "",
    fuGradeOfEncephalopathy: "",
    fuChildPughScore: "",
    fuLiverBiopsyStage: "",
    fuStagingDateLiverBiopsy: "",
    fuDiagnosis: "",
    fuTreatmentRegimen: "",
    fuNextAppointment: "",
    fuClinicalName: "",
    fuOutcome: "",
    fuRemark: "",
  };

  const FollowupFormValidationSchema = yup.object({
    fuDateOfVisit: yup.date().required("Date of visit is required"),
    fuWeight: isOperationUpdate ? yup.mixed() : yup.number(),
    fuHeight: isOperationUpdate ? yup.mixed() : yup.number(),
    // fuBmi: isOperationUpdate ? yup.mixed() : yup.number(),
    fuBloodPressure: isOperationUpdate ? yup.mixed() : yup.number(),
    fuHbsag: isOperationUpdate ? yup.mixed() : yup.number(),
    fuHbsagQuantification: isOperationUpdate ? yup.mixed() : yup.number(),
    fuHbeag: isOperationUpdate ? yup.mixed() : yup.number(),
    fuHbvDna: isOperationUpdate ? yup.mixed() : yup.number(),
    fuHbvDnaStatus: isOperationUpdate ? yup.mixed() : yup.string(),
    fuAlt: isOperationUpdate ? yup.mixed() : yup.number(),
    fuAst: isOperationUpdate ? yup.mixed() : yup.number(),
    fuPlt: isOperationUpdate ? yup.mixed() : yup.number(),
    fuTotalBilirubin: isOperationUpdate ? yup.mixed() : yup.number(),
    fuDirectBilirubin: isOperationUpdate ? yup.mixed() : yup.number(),
    fuAlbumin: isOperationUpdate ? yup.mixed() : yup.number(),
    fuApriScore: isOperationUpdate ? yup.mixed() : yup.number(),
    fuFib4: isOperationUpdate ? yup.mixed() : yup.number(),
    fuProthrombinTime: isOperationUpdate ? yup.mixed() : yup.number(),
    fuUrea: isOperationUpdate ? yup.mixed() : yup.number(),
    fuCreatinine: isOperationUpdate ? yup.mixed() : yup.number(),
    fuUltrasoundScan: isOperationUpdate ? yup.mixed() : yup.string(),
    fuAfp: isOperationUpdate ? yup.mixed() : yup.number(),
    fuFibroscan: isOperationUpdate ? yup.mixed() : yup.string(),
    fuCtScan: isOperationUpdate ? yup.mixed() : yup.string(),
    fuAscites: isOperationUpdate ? yup.mixed() : yup.string(),
    fuSeverityOfAscites: isOperationUpdate ? yup.mixed() : yup.string(),
    fuGradeOfEncephalopathy: isOperationUpdate ? yup.mixed() : yup.string(),
    fuChildPughScore: isOperationUpdate ? yup.mixed() : yup.string(),
    fuLiverBiopsyStage: isOperationUpdate ? yup.mixed() : yup.string(),
    fuStagingDateLiverBiopsy: isOperationUpdate ? yup.mixed() :yup.date(),
    fuDiagnosis: isOperationUpdate ? yup.mixed() : yup.string(),
    fuTreatmentRegimen: isOperationUpdate ? yup.mixed() : yup.string(),
    fuNextAppointment: isOperationUpdate ? yup.mixed() :yup.date(),
    fuClinicalName: isOperationUpdate ? yup.mixed() : yup.string(),
    fuOutcome: isOperationUpdate ? yup.mixed() : yup.string(),
    fuRemark: isOperationUpdate ? yup.mixed() : yup.string(),
  });

  const formik = useFormik({
    initialValues: followupFormIntialValue,
    onSubmit,
    validationSchema: FollowupFormValidationSchema,
  });
  return { formik };
};
